Don't require dataclasses for python 3.7+
conda-forge/black-feedstock pull request #28
Opened 2021-09-18 16:41 UTC by jamestwebber

dataclasses is now in the standard library and shouldn't be installed

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

2021-09-18 16:42 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [31]

2021-09-18 16:42 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-09-18 16:43 UTC, jamestwebber commented
@conda-forge-admin, please rerender

2021-09-18 17:30 UTC, xhochy requested changes
This is a noarch python package, the change will break it for older versions. Newer ones don't care about the empty dependency.

2021-09-18 17:32 UTC, jamestwebber commented
Hm okay. I have had issues in the past with dependencies like this, and in general it's nice to not have irrelevant requirements installed in my environment. But if this would break things then I will close.

2021-09-18 17:32 UTC, closed without merging

2021-09-19 05:32 UTC, xhochy commented
>  I have had issues in the past with dependencies like this,

At least when these dependencies come from conda-forge, they should either be empty or don't have any impact. If they are problematic, please open an issue describing that. We have them listed in multiple places as having `noarch: python` packages instead of version specific ones simplifies maintenance of these packages by a lot.