improve dependecies/remove noarch
conda-forge/black-feedstock pull request #46
Opened 2022-07-29 09:55 UTC by carlodri

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2022-07-29 09:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-07-29 09:56 UTC, carlodri commented
@conda-forge-admin please rerender

2022-07-29 10:08 UTC, carlodri commented
something weird going on... selectors for `typed-ast` seem not to work properly?

2022-07-29 11:43 UTC, carlodri commented
@conda-forge/black let me know your thoughts on this (and on the selector not working, if you have a hint)

2022-08-01 12:54 UTC, deantvv commented
@carlodri It seems like conda-build is smart enough to drop the `typed-ast` if it isn't actually used in build. After making a few [changes](https://github.com/conda-forge/black-feedstock/commit/bfd1af8f2fc47cd78b85bd19b6c20a149843f5d0), it seems to build and passes tests on my local environment.

2022-08-02 16:52 UTC, carlodri commented
@conda-forge-admin please rerender

2022-08-02 17:05 UTC, carlodri commented
> @carlodri It seems like conda-build is smart enough to drop the `typed-ast` if it isn't actually used in build. After making a few [changes](https://github.com/conda-forge/black-feedstock/commit/bfd1af8f2fc47cd78b85bd19b6c20a149843f5d0), it seems to build and passes tests on my local environment.

I'm not sure it is a good idea to release all constraints on the `pin_subpackage`... but I'm really not sure of what it does exactly.

2022-08-03 13:38 UTC, deantvv commented
We need to release at least `exact=True` for `pin_subpackage`  because when `exact=True` it will include build variant which won't work in this case because only `black` is built for different variants but other packages are built with `noarch: python`.

We also need following diff to make conda-build include `typed-ast` when building that way it will include `typed-ast` in dependencies.
```diff
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index 3b071d6..0bd2f32 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -24,6 +24,7 @@ outputs:
         - python
         - pip
         - setuptools_scm
+        - typed-ast >=1.4.2  # [py<38 and python_impl == 'cpython']
       run:
         - python
         - click >=8.0.0
```

2022-08-03 20:17 UTC, carlodri commented
@conda-forge-admin please rerender

2022-08-03 20:23 UTC, carlodri commented
> We need to release at least `exact=True` for `pin_subpackage` because when `exact=True` it will include build variant which won't work in this case because only `black` is built for different variants but other packages are built with `noarch: python`.

thanks for the insight! But shouldn't we constrain it at least to the same `x.x.x` version as in the black recipe output? As you can see I tried using `max_pin` but doesn't seem to help...

2022-08-04 13:09 UTC, deantvv commented
> thanks for the insight! 

It turns out that my "insight" is wrong. The reason why `typed-ast` kept getting drop is because `python_impl == 'cpython'` is False so the whole line is removed. So I start looking why there isn't `python_impl` in our build. It turns out that we only support `python_impl=='cpython'` so rerender never add `python_impl: cpython` to the build. We could drop `python_impl == 'cpython'` for now and hopefully the CI will turn green.

> To build your python package for pypy, wait for the bot to send a PR and contact conda-forge/bot team if a PR is not sent after the dependencies have been built. [conda-forge document](https://conda-forge.org/docs/maintainer/knowledge_base.html)

If we want to support `pypy` we will need to have all dependencies available in either noarch or pypy build. Now we still have `click` and `tomli` only available in `cpython` build.

> But shouldn't we constrain it at least to the same x.x.x version as in the black recipe output? As you can see I tried using max_pin but doesn't seem to help...

I didn't see why you think it isn't the case. In my local build, it constrain to `>=x.x.x,<x.x.x+1`

2022-08-04 13:14 UTC, deantvv requested changes
> thanks for the insight! 

It turns out that my "insight" is wrong. The reason why `typed-ast` kept getting drop is because `python_impl == 'cpython'` is False so the whole line is removed. So I start looking why there isn't `python_impl` in our build. It turns out that we only support `python_impl=='cpython'` so rerender never add `python_impl: cpython` to the build. We could drop `python_impl == 'cpython'` for now and hopefully the CI will turn green.

> To build your python package for pypy, wait for the bot to send a PR and contact conda-forge/bot team if a PR is not sent after the dependencies have been built. [conda-forge document](https://conda-forge.org/docs/maintainer/knowledge_base.html)

If we want to support `pypy` we will need to have all dependencies available in either noarch or pypy build. Now we still have `click` and `tomli` only available in `cpython` build.

> But shouldn't we constrain it at least to the same x.x.x version as in the black recipe output? As you can see I tried using max_pin but doesn't seem to help...

I didn't see why you think it isn't the case. In my local build, it constrain to `>=x.x.x,<x.x.x+1`

2022-08-04 13:14 UTC, deantvv commented on recipe/meta.yaml
> +        - typed-ast >=1.4.2  # [py<38 and python_impl == 'cpython']
My "insight" is wrong, so please remove this line if you would.
```suggestion
```

2022-08-04 13:14 UTC, deantvv commented on recipe/meta.yaml
> +        - typed-ast >=1.4.2  # [py<38 and python_impl == 'cpython']
```suggestion
        + typed-ast >=1.4.2  # [py<38]
```

2022-08-05 14:37 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * Failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

2022-08-05 14:40 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-08-05 14:40 UTC, carlodri commented
@conda-forge-admin please rerender

2022-08-05 22:56 UTC, merged